MATPLOTLIB_TEMPLATE = (
    "text.color : (0.2, 0.2, 0.2)\n"
    "font.family : sans-serif\n"
    "\n"
    "# AXES\n"
    "axes.titlesize : 16\n"
    "axes.labelsize : 12\n"
    "axes.prop_cycle : "
    "cycler('color', [{colours}])\n"
    "axes.edgecolor : (0.1, 0.1, 0.1) # Normalized RGB colours (from 0 to 1 instead of 0 to 255)\n"
    "axes.labelcolor : (0.1, 0.1, 0.1)\n"
    "axes.linewidth : 1\n"
    "axes.spines.top : False\n"
    "axes.spines.right : False\n"
    "axes.spines.bottom : True\n"
    "axes.spines.left : True\n"
    "axes.grid : False\n"
    "\n"
    "# LINES\n"
    "\n"
    "lines.linewidth : 1.5\n"
    "lines.markeredgewidth : 0.0\n"
    "\n"
    "# SCATTER PLOT\n"
    "scatter.marker : .\n"
    "\n"
    "# TICKS\n"
    "xtick.labelsize : 8\n"
    "xtick.color : (0.2, 0.2, 0.2)\n"
    "xtick.direction : in\n"
    "ytick.labelsize : 8\n"
    "ytick.color : (0.2, 0.2, 0.2)\n"
    "ytick.direction : in\n"
    "\n"
    "# FIGURE OUTPUT\n"
    "figure.figsize  : 7, 5\n"
    "figure.dpi : 300\n"
    "savefig.dpi : 300"
)
